version: '3'
services:
  mate-desktop:
    environment:
    - PASSWORD=mate
    - USER=mate
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/mate-desktop-german-20.10:1
    restart: always
    stdin_open: true
    tty: true
    ports:
    - 4000:4000/tcp
    - 2222:22/tcp
